#Mobcash Created by Feazes[retired]
#Updated to 8 12/13/2020 by EonZombie

Mobcash:
    #Don't edit the Version.
    Version: 8.0
    #Toggle messages when you kill a mob
    Message-enabled: true
    #Message sent to a player who just killed a mob
    #Replacements can be used: colors &(1-9 | a-f), RGB (example:&#abcdef) or words <(player | mob | money)>
    Message: "&6Good job &c<player>! you just killed a &c<mob> &6and recieved &c$<money>."
    #Send message as ACTIONBAR or as regular MESSAGE
    Message-Type: ACTIONBAR
    #Disable cash for ways mobs have been spawned
	#Spawn reasons: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
    Disable-Spawns: #add spawn reasons here, (lowercase)
        - spawner
    #Worlds that the plugin is disabled in
    DisabledWorlds:
        - disabled_world
    #Settings for the amount of cash players get for killing mobs
    Mobs:
        #Group Mob Settings
        #This is for people who want to set the same price for all mobs in a group
		#By default: mobs will get these values if not further defined
		#List of mobs per group:
		#Checked: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Creature.html
		#Monsers: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Monster.html
		#Boss: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Boss.html
		#Others: Passive
        GroupSettings:
            PassiveMobs:
                min: 5
                max: 5
            Monsters:
                min: 10
                max: 10
            Bosses:
                min: 40
                max: 40
        #Individual Mob Settings, use lovercase names of entity type: 
		# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
        #Format:
		#name:
		#    min: amount 
		#    max: amount
        #If you want the disable the mob put 0 as the amount for min and max value
        CustomMobSettings:
            bat:
                min: 3
                max: 3
            blaze:
                min: 10
                max: 10
    PVP:
    #Do you want to allow players to get money for killing other players?
        Enabled: true
		Messages-Enabled: true
    #How much should killer take from victim?
        Killer-takes:
            min: 10
            max: 10
    #Message to a killer:
        KillerMessage: "&c<killer>&6! you  killed &c&<victim> &6and gained &c<money>!"
    #Message to killed player:
        VictimMessage: "&c<victim>&6! you were killed by &c&<killer> &6and lost &c<money>!"