name: Mobcash
author: EonZombie & Feazes
main: me.Feazes.plugins.mobcash.Main
version: 8.0
description: MobCash gives players money when they kill a mob/player.
depend: [Vault]

commands:
    mobcash:
        description: Shows information about the plugin.
        permission: mobcash.admin
        permission-message: "You don't have the permission for this command!"