#Mobcash Created by Feazes[retired]
#Updated to 8 12/16/2020 by EonZombie
#Do not use TABS, use SPACES, you can pre-check your config
#(It does not check for tabs in comments, though) here: https://codebeautify.org/yaml-validator

Mobcash:
#Don't edit the Version.
    Version: 8.2
#Toggle messages when you kill a mob
    Message-enabled: true
#Message sent to a player who just killed a mob
#Replacements can be used: colors &(1-9 | a-f), RGB (example:&#abcdef) or words <(player | mob | money)>
    Message: "&6Good job &c<player>&r! &6You just killed a &c<mob> &6and recieved &c$<money>."
#Send message as ACTIONBAR or as regular MESSAGE
    Message-Type: ACTIONBAR
#Disable cash for ways mobs have been spawned
#Spawn reasons:https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
    Disable-Spawns: #add spawn reasons here, (lowercase)
        - spawner
#Worlds that the plugin is disabled in
    DisabledWorlds:
        - disabled_world
#Settings for the amount of cash players get for killing mobs
    Mobs:
#Group Mob Settings
#This is for people who want to set the same price for all mobs in a group
#By default: mobs will get these values if not further defined
#List of mobs per group:
#Checked:https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Creature.html
#Monsers:https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Monster.html
#Boss:https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Boss.html
#Others: Passive
#Types: CONSTANT amount:x
# or RANDOM min:a max:b

        GroupSettings:
            PassiveMobs:
                type: RANDOM
                min: 0.1
                max: 5
            Monsters:
                type: RANDOM
                min: 0.1
                max: 10
            Bosses:
                type: CONSTANT
                amount: 100
#Individual Mob Settings, use lovercase names of entity type: 
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
#Types: CONSTANT amount:x
# or RANDOM min:a max:b

        CustomMobSettings:
            bat:
                type: RANDOM
                min: 0.1
                max: 3
            blaze:
                type: CONSTANT
                amount: 10
    PVP:
#Do you want to allow players to get money for killing other players?
        Enabled: true
        Messages-Enabled: true
#How much should killer take from victim?
#Types: CONSTANT amount:x
#       RANDOM min:a max:b
#       PERCENTAGE amount:x
        Killer-takes:
            type: PERCENTAGE
            amount: 5
#Message to a killer:
        KillerMessage: "&c<killer>&r! &6You  killed &c&<victim> &6and gained &c<money>!"
#Message to killed player:
        VictimMessage: "&c<victim>&r! &6You were killed by &c&<killer> &6and lost &c<money>!"